version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - backend-net

  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: toilet
      POSTGRES_PASSWORD: toilet123
      POSTGRES_DB: toiletfinder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # ↓ 여기에 넣은 .sql/.sh 파일은 "데이터 디렉토리가 비어있을 때" 1회 자동 실행됨
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toilet -d toiletfinder"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - backend-net

volumes:
  redis_data:
  postgres_data:

networks:
  backend-net:
    driver: bridge