spring:
  application:
    name: ddongkan
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
  datasource:
    url: jdbc:postgresql://localhost:5432/toiletfinder
    username: toilet
    password: toilet123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info   # ???? "*" ?
  endpoint:
    health:
      show-details: always     # ?? ??(REDIS/DB ?) ????
      probes:
        enabled: true          # liveness/readiness ??? ???
  health:
    redis:
      enabled: true            # Redis ?? ??(?? true)
    db:
      enabled: true            # DB ?? ??(?? true)
